# -*- coding: utf-8 -*-
"""Scraping Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjpWP98v8FSow_Mx5W-CNQ-geICa3mc1
"""

!pip install google-play-scraper

"""# 1. Import Library"""

from google_play_scraper import reviews_all, Sort
import pandas as pd
import csv

"""# 2. Scraping Dataset"""

# Mengambil semua ulasan dari aplikasi dengan ID 'com.whatsapp' di Google Play Store.
# Proses scraping mungkin memerlukan beberapa saat tergantung pada jumlah ulasan yang ada.
scrapreview = reviews_all(
    'com.whatsapp',             # ID aplikasi
    lang='id',                  # Bahasa ulasan (default: 'en')
    country='id',               # Negara (default: 'us')
    sort=Sort.MOST_RELEVANT,    # Urutan ulasan (default: Sort.MOST_RELEVANT)
    count=20000                 # Jumlah maksimum ulasan yang ingin diambil
)
scrapreview = scrapreview[:20000]

"""# 3. Simpan Dataset"""

with open('ulasan_aplikasi_whatsapp.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file, quoting=csv.QUOTE_ALL)  # <-- tambahkan quoting
    writer.writerow(['Review']) # Menulis header kolom
    for review in scrapreview:
        writer.writerow([review['content']]) # Menulis setiap ulasan ke baris baru

"""# 4. Melihat Dataset"""

# Membuat DataFrame
app_reviews_df = pd.DataFrame(scrapreview)

# Menampilkan informasi dataset
display(app_reviews_df.head())

# Menyimpan ke CSV
app_reviews_df.to_csv('ulasan_aplikasi_whatsapp2.csv', index=False)

app_reviews_df.info()

